name: lz-development - tagging-with-yor - Deploy

pool: 
  vmImage: 'ubuntu-latest'

trigger:
 - none

variables:
  - group: var-terraform-backend

stages:
  - stage: Plan
    jobs:
      - job: Terraform_plan
        steps:
          - checkout: self
          - task: Bash@3
            displayName: "Terraform init"
            inputs:
              targetType: 'inline'
              script: |
                set -e 
                terraform init -input=false -no-color \
                  -backend-config="resource_group_name=$(AZURE_RESOURCE_GROUP_NAME)" \
                  -backend-config="storage_account_name=$(AZURE_STORAGE_ACCOUNT_NAME)" \
                  -backend-config="container_name=tfstate" \
                  -backend-config="key=azure-auto-tagging-with-terratag.ado.tfstate" \
                  -backend-config="use_oidc=true"

              workingDirectory: "$(System.DefaultWorkingDirectory)"
            env:
              # get values from the variable group 
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUB_ID)
              ARM_SKIP_PROVIDER_REGISTRATION: true

          - task: Bash@3
            displayName: "Add metadata tagging using Yor"
            inputs:
              targetType: 'inline'
              script: |
                # download Yor
                curl -s -k https://api.github.com/repos/bridgecrewio/yor/releases/latest | jq '.assets[] | select(.name | contains("linux_386")) | select(.content_type | contains("gzip")) | .browser_download_url' -r | awk '{print "curl -L -k " $0 " -o yor.tar.gz"}' | sh
                tar -xf yor.tar.gz
                chmod +x yor
                ./yor --version

                # run Yor
                yor tag --directory tagging --dry-run --parsers Terraform
                yor tag --directory tagging --parsers Terraform

                # show folder contents
                ls -al

              workingDirectory: "$(System.DefaultWorkingDirectory)"
            env:
              # get values from the variable group 
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUB_ID)
              ARM_SKIP_PROVIDER_REGISTRATION: true
              
          - task: Bash@3
            displayName: "Terraform plan"
            inputs:
              targetType: 'inline'
              script: |
                set -e 
                echo "Execute: TF Plan"
                terraform plan -input=false -var-file "./terraform.tfvars" -out='tfplan'
              workingDirectory: "$(System.DefaultWorkingDirectory)"
            env:
              # get values from the variable group 
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUB_ID)
              ARM_SKIP_PROVIDER_REGISTRATION: true

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)'
              includeRootFolder: false
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tgz'
              replaceExistingArchive: true
              displayName: 'Create Plan Artifact'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(Build.BuildId)-tfplan'
              publishLocation: 'Container'
              displayName: 'Publish Plan Artifact'
  
  - stage: Deploy
    dependsOn: [ 'Plan' ]
    jobs:
    - deployment: Terraform_Deploy
      continueOnError: false
      timeoutInMinutes: 600
      strategy:
       runOnce:
        deploy:
          steps:
            - checkout: none

            - task: DownloadBuildArtifacts@0
              inputs:
                artifactName: '$(Build.BuildId)-tfplan'
                displayName: 'Download Plan Artifact'

            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: '$(System.ArtifactsDirectory)/$(Build.BuildId)-tfplan/$(Build.BuildId).tgz'
                destinationFolder: "$(System.DefaultWorkingDirectory)"
                cleanDestinationFolder: false
                overwriteExistingFiles: true
                displayName: 'Extract Terraform Plan Artifact'
            
            - task: Bash@3
              displayName: "Terraform apply"
              inputs:
                targetType: 'inline'
                script: |
                  set -e
                  echo "Execute: TF Init"
                  terraform init -input=false

                  echo "Execute: TF Apply"
                  terraform apply -auto-approve -input=false tfplan
                workingDirectory: "$(System.DefaultWorkingDirectory)"
              env:
                ARM_TENANT_ID: $(AZURE_TENANT_ID)
                ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
                ARM_SUBSCRIPTION_ID: $(AZURE_SUB_ID)
                ARM_SKIP_PROVIDER_REGISTRATION: true
                