name: dev - tagging-with-terratag (TerraformTask) - Deploy

pool: 
  vmImage: 'ubuntu-latest'

trigger:
 - none

variables:
  - group: var-terraform-backend

stages:
  - stage: Plan
    jobs:
      - job: Terraform_plan
        steps:
          - checkout: self
            fetchDepth: 0

          - task: TerraformTaskV4@4
            name: 'Terraform_Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: '$(AZURE_SVC_NAME)'
              backendAzureRmResourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
              backendAzureRmStorageAccountName: '$(AZURE_STORAGE_ACCOUNT_NAME)'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'azure-auto-tagging-with-terratag.ado.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terratag'
            env:
              ARM_USE_AZUREAD: true
              ARM_USE_OIDC: true

          - task: Bash@3
            name: 'Add_metadata_tagging_using_Terratag'
            displayName: 'Add metadata tagging using Terratag'
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/terratag'
              targetType: 'inline'
              script: |
                ./terratag.sh

          - task: TerraformTaskV4@4
            displayName: 'Terraform_Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'   

          - task: TerraformTaskV4@4
            name: 'Terraform_Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-input=false -var-file "./terraform.tfvars" -out=tfplan -var="default_subscription_id=$(SUBSCRIPTION_ID)" -var="deployed_from=ADO"'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terratag'
              environmentServiceNameAzureRM: '$(AZURE_SVC_NAME)'
            env:
              ARM_USE_AZUREAD: true
              ARM_USE_OIDC: true

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/terratag/tfplan'
              includeRootFolder: false
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tgz'
              replaceExistingArchive: true
              displayName: 'Create Plan Artifact'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(Build.BuildId)-tfplan'
              publishLocation: 'Container'
              displayName: 'Publish Plan Artifact'
  
  - stage: Deploy
    dependsOn: [ 'Plan' ]
    jobs:
    - deployment: Terraform_Deploy
      environment: 'development'
      continueOnError: false
      timeoutInMinutes: 600
      strategy:
       runOnce:
        deploy:
          steps:
            - checkout: none

            - task: DownloadBuildArtifacts@0
              inputs:
                artifactName: '$(Build.BuildId)-tfplan'
                displayName: 'Download Plan Artifact'

            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: '$(System.ArtifactsDirectory)/$(Build.BuildId)-tfplan/$(Build.BuildId).tgz'
                destinationFolder: "$(System.DefaultWorkingDirectory)"
                cleanDestinationFolder: false
                overwriteExistingFiles: true
                displayName: 'Extract Terraform Plan Artifact'
            
            - task: TerraformTaskV4@4
              name: 'Terraform_Apply'
              inputs:
                provider: 'azurerm'
                command: 'apply'
                commandOptions: '-auto-approve -input=false tfplan'
                workingDirectory: '$(System.DefaultWorkingDirectory)'
                environmentServiceNameAzureRM: '$(AZURE_SVC_NAME)'
              env:
                ARM_USE_AZUREAD: true
                ARM_USE_OIDC: true